/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Edward' at '16. 9. 23 오후 12:17' with Gradle 2.14.1
 *
 * @author Edward, @date 16. 9. 23 오후 12:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
